# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site setting
title: Learning libs
email: tl2f@outlook.com
description: >
 Keep learning.
baseurl: ""
permalink: /:categories/:title.html # permalink special page url. # permalink: /:categories/:year/:month/:day/:title/  if permalink:none then url should be /:categories/:title

exclude: [Front-End-Repos, github-page-knowledges] # exclude generate files under special folder

plugins: [jekyll-paginate]
paginate: 1
paginate_path: "/blogs/page:num/"

defaults:
  - scope:
      path: ""
    values:
       layout: "default"
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "blog"
