# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# basic Site setting
title: Learning libs #你博客的标题
SEOTitle: front-end #显示在浏览器上搜索的时候显示的标题
email: tl2f@outlook.com
header-img: ''  	#显示在首页的背景图片
description: >
 Keep learning and practice more.
baseurl: ""
url: ""          # 这个就是填写你的博客地址
keyword: "front-end, front end" #关键词

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "说点装逼的话。。。"
sidebar-avatar:      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
weibo_username:     username
zhihu_username:     username
github_username:    username
facebook_username:  username
jianshu_username:	6b3bc8783ffb
#新加入了简书，jianshu_id 在你打开你的简书主页后的地址如：http://www.jianshu.com/u/e71990ada2fd中，后面这一串数字：e71990ada2fd

permalink: /:categories/:title.html # permalink special page url. # permalink: /:categories/:year/:month/:day/:title/  if permalink:none then url should be /:categories/:title

exclude: [Front-End-Repos, github-page-knowledges] # exclude generate files under special folder

plugins: [jekyll-paginate]
paginate: 12
paginate_path: "/blogs/page:num/" # files generate folder is "blogs" and the subfolder is page2,page3....page:num.

defaults:
  - scope:
      path: ""
    values:
       layout: "default"
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "blog"
