theme: jekyll-theme-architect
permalink: none # permalink: /:categories/:year/:month/:day/:title/  if permalink:none then url should be /:categories/:title
plugins: [jekyll-paginate]
paginate: 1
paginate_path: "/blog/page:num/"
